from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH

doc = Document()
title = doc.add_heading('MODULE 3.4: TRÍCH XUẤT VÀ LỰA CHỌN ĐẶC TRƯNG (FEATURE EXTRACTION & SELECTION)', 0)
title.alignment = WD_ALIGN_PARAGRAPH.CENTER

doc.add_heading('1. Giới Thiệu', 1)
doc.add_paragraph('Module Feature Extraction & Selection mô tả cách trích xuất & lựa chọn đặc trưng quan trọng.')
doc.add_paragraph('Gồm 2 phần chính: Feature Selection + Class Imbalance Handling', style='List Bullet')

doc.add_heading('2. 3.4.1: Lựa Chọn Đặc Trưng (Feature Selection)', 2)

doc.add_heading('2.1 Khái Niệm Feature Selection', 2)
doc.add_paragraph('Định nghĩa:', style='List Bullet')
doc.add_paragraph('Chọn subset của features để cải thiện model performance', style='List Bullet 2')
doc.add_paragraph('Loại bỏ features không quan trọng', style='List Bullet 2')
doc.add_paragraph('Giảm overfitting & computational cost', style='List Bullet 2')

doc.add_heading('2.2 Các Phương Pháp Lựa Chọn Đặc Trưng', 2)
doc.add_paragraph('1. Univariate Feature Selection:', style='List Bullet')
doc.add_paragraph('Chi-square test cho categorical', style='List Bullet 2')
doc.add_paragraph('F-test cho regression', style='List Bullet 2')
doc.add_paragraph('Correlation analysis', style='List Bullet 2')
doc.add_paragraph('2. Model-based Selection:', style='List Bullet')
doc.add_paragraph('Feature importance từ RandomForest', style='List Bullet 2')
doc.add_paragraph('Coefficient từ Logistic Regression', style='List Bullet 2')
doc.add_paragraph('3. Wrapper Methods:', style='List Bullet')
doc.add_paragraph('Recursive Feature Elimination (RFE)', style='List Bullet 2')
doc.add_paragraph('Forward/Backward selection', style='List Bullet 2')

doc.add_heading('2.3 Sự Kết Hợp các Phương Pháp', 2)
doc.add_paragraph('Trong dự án này:', style='List Bullet')
doc.add_paragraph('8 trường categorical (OneHot → nhiều features)', style='List Bullet 2')
doc.add_paragraph('2 trường text (TF-IDF → ~100 features)', style='List Bullet 2')
doc.add_paragraph('Tổng: ~130-150 features', style='List Bullet 2')
doc.add_paragraph('Lựa chọn top features dựa feature importance', style='List Bullet 2')

doc.add_heading('2.4 Lý Do Chọn 8 Trường Categorical + TF-IDF', 2)
doc.add_paragraph('Categorical (6 select fields + 2 targets):', style='List Bullet')
doc.add_paragraph('Direct relationship với target ngành', style='List Bullet 2')
doc.add_paragraph('Easy to interpret & explainable', style='List Bullet 2')
doc.add_paragraph('High signal-to-noise ratio', style='List Bullet 2')
doc.add_paragraph('TF-IDF (2 text fields):', style='List Bullet')
doc.add_paragraph('Capture semantic meaning', style='List Bullet 2')
doc.add_paragraph('Top 100 terms by TF-IDF weight', style='List Bullet 2')
doc.add_paragraph('Reduce dimensionality từ full vocabulary', style='List Bullet 2')

doc.add_heading('2.5 Lợi Ích của 8 Trường được Chọn', 2)
doc.add_paragraph('✓ Rất quan trọng cho dự đoán ngành', style='List Bullet')
doc.add_paragraph('✓ Bắt buộc trong form (required fields)', style='List Bullet')
doc.add_paragraph('✓ Dễ giải thích & minh bạch', style='List Bullet')
doc.add_paragraph('✓ Cân bằng giữa coverage & complexity', style='List Bullet')

doc.add_heading('2.6 Output của Feature Selection', 2)
doc.add_paragraph('Features được giữ lại:', style='List Bullet')
doc.add_paragraph('6 categorical fields (OneHot encoded)', style='List Bullet 2')
doc.add_paragraph('2 text fields (TF-IDF vectorized)', style='List Bullet 2')
doc.add_paragraph('Total: ~130-150 features', style='List Bullet 2')
doc.add_paragraph('Lưu trữ:', style='List Bullet')
doc.add_paragraph('ohe.pkl (OneHotEncoder)', style='List Bullet 2')
doc.add_paragraph('tfidf.pkl (TfidfVectorizer)', style='List Bullet 2')

doc.add_heading('3. 3.4.2: Xử Lý Mất Cân Bằng Lớp (Class Imbalance)', 2)

doc.add_heading('3.1 Khái Niệm Class Imbalance', 2)
doc.add_paragraph('Định nghĩa:', style='List Bullet')
doc.add_paragraph('Không có đủ samples cho mỗi class', style='List Bullet 2')
doc.add_paragraph('Ví dụ: Class A có 500 samples, Class B có 50 samples', style='List Bullet 2')
doc.add_paragraph('Model bias towards majority class', style='List Bullet 2')

doc.add_heading('3.2 Phân Tích Class Imbalance trong Dự Án', 2)
doc.add_paragraph('Dữ liệu Synthetic được tạo balanced:', style='List Bullet')
doc.add_paragraph('~80 samples per major × 15 majors = 1200 total', style='List Bullet 2')
doc.add_paragraph('Mỗi class có ~6.7% của data', style='List Bullet 2')
doc.add_paragraph('Không có major nào dominates', style='List Bullet 2')

doc.add_heading('3.3 Các Phương Pháp Xử Lý Class Imbalance', 2)
doc.add_paragraph('1. Oversampling:', style='List Bullet')
doc.add_paragraph('Nhân lên minority classes', style='List Bullet 2')
doc.add_paragraph('SMOTE: Synthetic Minority Over-sampling', style='List Bullet 2')
doc.add_paragraph('2. Undersampling:', style='List Bullet')
doc.add_paragraph('Giảm majority classes', style='List Bullet 2')
doc.add_paragraph('Random undersampling', style='List Bullet 2')
doc.add_paragraph('3. Balanced Sampling:', style='List Bullet')
doc.add_paragraph('Tạo balanced synthetic data', style='List Bullet 2')
doc.add_paragraph('Chính xác như dự án (80 per major)', style='List Bullet 2')

doc.add_heading('3.4 Lựa Chọn Phương Pháp Trong Dự Án', 2)
doc.add_paragraph('Phương pháp: Balanced Synthetic Data Generation', style='List Bullet')
doc.add_paragraph('Lý do:', style='List Bullet 2')
doc.add_paragraph('Dễ implement & hiểu', style='List Bullet 2')
doc.add_paragraph('Garantee balanced distribution', style='List Bullet 2')
doc.add_paragraph('Tránh data leakage', style='List Bullet 2')
doc.add_paragraph('Realistic feature values', style='List Bullet 2')

doc.add_heading('3.5 Metrics Phù Hợp cho Class Imbalance', 2)
doc.add_paragraph('Accuracy: KHÔNG phù hợp (misleading)', style='List Bullet')
doc.add_paragraph('Precision: How many predicted positives correct', style='List Bullet')
doc.add_paragraph('Recall: How many true positives found', style='List Bullet')
doc.add_paragraph('F1-Score: Harmonic mean of Precision & Recall', style='List Bullet')
doc.add_paragraph('Macro-averaged F1: Average F1 across all classes', style='List Bullet')

doc.add_heading('3.6 Xử Lý Class Imbalance Trong Training', 2)
doc.add_paragraph('Bước 1: Tạo balanced training set', style='List Number')
doc.add_paragraph('80% balanced data', style='List Bullet 2')
doc.add_paragraph('Bước 2: Train model', style='List Number')
doc.add_paragraph('RandomForest tự xử lý imbalance tốt', style='List Bullet 2')
doc.add_paragraph('Bước 3: Calibrate probabilities', style='List Number')
doc.add_paragraph('CalibratedClassifierCV', style='List Bullet 2')
doc.add_paragraph('Bước 4: Evaluate on balanced test set', style='List Number')
doc.add_paragraph('20% balanced data', style='List Bullet 2')

doc.add_heading('3.7 Output của Class Imbalance Handling', 2)
doc.add_paragraph('Model không bias towards một major', style='List Bullet')
doc.add_paragraph('Balanced predictions across all classes', style='List Bullet')
doc.add_paragraph('Fair recommendations cho tất cả students', style='List Bullet')

doc.add_heading('4. Tổng Quát Quy Trình', 1)
doc.add_paragraph('Bước 1: Load cleaned, split data', style='List Number')
doc.add_paragraph('Bước 2: Select 8 important features', style='List Number')
doc.add_paragraph('6 categorical (OneHot)', style='List Bullet 2')
doc.add_paragraph('2 text (TF-IDF)', style='List Bullet 2')
doc.add_paragraph('Bước 3: Ensure balanced training data', style='List Number')
doc.add_paragraph('~80 per major', style='List Bullet 2')
doc.add_paragraph('Bước 4: Train model', style='List Number')
doc.add_paragraph('RandomForest classifier', style='List Bullet 2')
doc.add_paragraph('Bước 5: Evaluate on balanced test set', style='List Number')
doc.add_paragraph('20% balanced data', style='List Bullet 2')

doc.add_heading('5. Kết Luận', 1)
doc.add_paragraph('✓ Feature Selection → select important features', style='List Bullet')
doc.add_paragraph('✓ 8 trường + TF-IDF → balanced coverage', style='List Bullet')
doc.add_paragraph('✓ Class Imbalance Handling → fair model', style='List Bullet')
doc.add_paragraph('✓ Balanced data → better performance', style='List Bullet')
doc.add_paragraph('✓ Proper metrics → accurate evaluation', style='List Bullet')

doc.save('FEATURE_EXTRACTION_MODULE.docx')
print("✅ Feature Extraction & Selection Module completed: FEATURE_EXTRACTION_MODULE.docx")
