from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH

doc = Document()
title = doc.add_heading('MODULE 6: TRIỂN KHAI SẢN PHẨM (DEPLOYMENT)', 0)
title.alignment = WD_ALIGN_PARAGRAPH.CENTER

doc.add_heading('1. Giới Thiệu', 1)
doc.add_paragraph('Module Deployment mô tả cách triển khai hệ thống lên production.')
doc.add_paragraph('Gồm 6 thành phần chính:', style='List Bullet')

doc.add_heading('2. 5.4.1: AI Model Framework (Joblib & Pickle)', 2)
doc.add_paragraph('Lưu trữ & tải models đã train:', style='List Bullet')
doc.add_paragraph('rf_model.pkl: RandomForest model', style='List Bullet 2')
doc.add_paragraph('ohe.pkl: OneHotEncoder', style='List Bullet 2')
doc.add_paragraph('tfidf.pkl: TfidfVectorizer', style='List Bullet 2')
doc.add_paragraph('Cách tải:', style='List Bullet')
doc.add_paragraph('model = joblib.load("models/rf_model.pkl")', style='List Bullet 2')
doc.add_paragraph('Lợi ích:', style='List Bullet')
doc.add_paragraph('Nhanh: không cần retraining', style='List Bullet 2')
doc.add_paragraph('Portable: có thể copy sang server khác', style='List Bullet 2')

doc.add_heading('3. 5.4.2: Data Management (Pandas)', 2)
doc.add_paragraph('Xử lý dữ liệu với Pandas:', style='List Bullet')
doc.add_paragraph('Load CSV: pd.read_csv("data/raw/students.csv")', style='List Bullet 2')
doc.add_paragraph('Transform: OneHot Encoding, TF-IDF', style='List Bullet 2')
doc.add_paragraph('Validate: Check required fields, data types', style='List Bullet 2')
doc.add_paragraph('Output: Feature vectors cho model', style='List Bullet 2')

doc.add_heading('4. 5.4.3: API Server (Flask)', 2)
doc.add_paragraph('Backend endpoints:', style='List Bullet')
doc.add_paragraph('GET /: Trang form', style='List Bullet 2')
doc.add_paragraph('POST /predict: Nhận input, trả Top 3', style='List Bullet 2')
doc.add_paragraph('GET /health: Kiểm tra status', style='List Bullet 2')
doc.add_paragraph('Flask setup:', style='List Bullet')
doc.add_paragraph('app = Flask(__name__)', style='List Bullet 2')
doc.add_paragraph('@app.route("/predict", methods=["POST"])', style='List Bullet 2')
doc.add_paragraph('Chạy: python app.py', style='List Bullet 2')

doc.add_heading('5. 5.4.4: DOM & Fetch API (JavaScript)', 2)
doc.add_paragraph('Frontend interactions:', style='List Bullet')
doc.add_paragraph('DOM manipulation: document.getElementById()', style='List Bullet 2')
doc.add_paragraph('Fetch API: fetch("/predict", {method: "POST"})', style='List Bullet 2')
doc.add_paragraph('Event listeners: addEventListener("click")', style='List Bullet 2')
doc.add_paragraph('Response handling: JSON.parse(), render results', style='List Bullet 2')

doc.add_heading('6. 5.4.5: Integration & Verification', 2)
doc.add_paragraph('Kiểm tra hệ thống:', style='List Bullet')
doc.add_paragraph('Bước 1: Start Flask server', style='List Bullet 2')
doc.add_paragraph('Bước 2: Open http://localhost:5000', style='List Bullet 2')
doc.add_paragraph('Bước 3: Fill form & submit', style='List Bullet 2')
doc.add_paragraph('Bước 4: Check results display', style='List Bullet 2')
doc.add_paragraph('Bước 5: Test chatbot functionality', style='List Bullet 2')

doc.add_heading('7. 5.4.6: Performance Metrics', 2)
doc.add_paragraph('Response time:', style='List Bullet')
doc.add_paragraph('Content-Based: ~100ms', style='List Bullet 2')
doc.add_paragraph('ML Prediction: ~50ms', style='List Bullet 2')
doc.add_paragraph('Total: ~160ms', style='List Bullet 2')
doc.add_paragraph('Accuracy:', style='List Bullet')
doc.add_paragraph('Test set accuracy: ~75-80%', style='List Bullet 2')
doc.add_paragraph('Precision per major: 60-90%', style='List Bullet 2')

doc.add_heading('8. Production Deployment', 1)
doc.add_paragraph('Bước 1: Setup environment trên server', style='List Number')
doc.add_paragraph('Bước 2: Install dependencies', style='List Number')
doc.add_paragraph('Bước 3: Upload models & data files', style='List Number')
doc.add_paragraph('Bước 4: Configure environment variables', style='List Number')
doc.add_paragraph('Bước 5: Run with production server (Gunicorn)', style='List Number')
doc.add_paragraph('Bước 6: Setup reverse proxy (Nginx)', style='List Number')
doc.add_paragraph('Bước 7: Enable SSL/HTTPS', style='List Number')

doc.add_heading('9. Kết Luận', 1)
doc.add_paragraph('✓ Joblib lưu trữ models hiệu quả', style='List Bullet')
doc.add_paragraph('✓ Pandas xử lý dữ liệu nhanh', style='List Bullet')
doc.add_paragraph('✓ Flask API đơn giản & mạnh mẽ', style='List Bullet')
doc.add_paragraph('✓ JavaScript Fetch tương tác mượt', style='List Bullet')
doc.add_paragraph('✓ System hoạt động ổn định & nhanh', style='List Bullet')

doc.save('DEPLOYMENT_MODULE.docx')
print("✅ Deployment Module completed: DEPLOYMENT_MODULE.docx")
