from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH

doc = Document()
title = doc.add_heading('MODULE 2: TIỀN XỬ LÝ DỮ LIỆU (DATA PREPROCESSING)', 0)
title.alignment = WD_ALIGN_PARAGRAPH.CENTER

doc.add_heading('1. Giới Thiệu', 1)
doc.add_paragraph('Module Data Preprocessing mô tả cách xử lý & chuẩn hóa dữ liệu trước khi huấn luyện model.')
doc.add_paragraph('Gồm 6 bước xử lý chính:', style='List Bullet')

doc.add_heading('2. 3.2.1: Làm Sạch Dữ Liệu (Data Cleaning)', 2)
doc.add_paragraph('Xử lý Missing Values:', style='List Bullet')
doc.add_paragraph('Kiểm tra NaN values', style='List Bullet 2')
doc.add_paragraph('Xóa rows có missing > 50%', style='List Bullet 2')
doc.add_paragraph('Fill missing với mode/median', style='List Bullet 2')
doc.add_paragraph('Xử lý Outliers:', style='List Bullet')
doc.add_paragraph('IQR method: Q3 + 1.5×IQR', style='List Bullet 2')
doc.add_paragraph('Z-score method: |z| > 3', style='List Bullet 2')
doc.add_paragraph('Xóa hoặc capping outliers', style='List Bullet 2')
doc.add_paragraph('Xử lý Duplicates:', style='List Bullet')
doc.add_paragraph('Kiểm tra exact duplicates', style='List Bullet 2')
doc.add_paragraph('Xóa hoàn toàn identical rows', style='List Bullet 2')

doc.add_heading('3. 3.2.2: Chuẩn Hóa Văn Bản Tiếng Việt (Normalization)', 2)
doc.add_paragraph('Remove diacritics:', style='List Bullet')
doc.add_paragraph('ă, ơ, ư, đ → a, o, u, d', style='List Bullet 2')
doc.add_paragraph('unicodedata.normalize("NFKD")', style='List Bullet 2')
doc.add_paragraph('Lowercase:', style='List Bullet')
doc.add_paragraph('Chuyển tất cả thành lowercase', style='List Bullet 2')
doc.add_paragraph('Strip whitespace:', style='List Bullet')
doc.add_paragraph('Remove leading/trailing spaces', style='List Bullet 2')
doc.add_paragraph('Remove special characters:', style='List Bullet')
doc.add_paragraph('Giữ lại chữ cái, số, space', style='List Bullet 2')

doc.add_heading('4. 3.2.3: Chuẩn Hóa Giá Trị Phân Loại (Categorical)', 2)
doc.add_paragraph('Mapping values:', style='List Bullet')
doc.add_paragraph('"Technology" → "cong nghe thong tin"', style='List Bullet 2')
doc.add_paragraph('"Business" → "quan tri kinh doanh"', style='List Bullet 2')
doc.add_paragraph('Consistency check:', style='List Bullet')
doc.add_paragraph('Verify all values known', style='List Bullet 2')
doc.add_paragraph('No typos or variations', style='List Bullet 2')

doc.add_heading('5. 3.2.4: Mã Hóa Dữ Liệu Phân Loại (One-Hot Encoding)', 2)
doc.add_paragraph('Bước 1: Tạo OneHotEncoder:', style='List Number')
doc.add_paragraph('ohe = OneHotEncoder(sparse_output=False)', style='List Bullet 2')
doc.add_paragraph('Bước 2: Fit trên training data:', style='List Number')
doc.add_paragraph('ohe.fit(categorical_data)', style='List Bullet 2')
doc.add_paragraph('Bước 3: Transform data:', style='List Number')
doc.add_paragraph('X_ohe = ohe.transform(categorical_data)', style='List Bullet 2')
doc.add_paragraph('Kết quả: 1D array → 2D matrix', style='List Bullet')
doc.add_paragraph('[technology] → [1, 0, 0, 0, ...]', style='List Bullet 2')
doc.add_paragraph('[business] → [0, 1, 0, 0, ...]', style='List Bullet 2')

doc.add_heading('6. 3.2.5: Xử Lý NLP cho Câu Tự Luận (TF-IDF)', 2)
doc.add_paragraph('Bước 1: Tạo TfidfVectorizer:', style='List Number')
doc.add_paragraph('tfidf = TfidfVectorizer(max_features=100)', style='List Bullet 2')
doc.add_paragraph('Bước 2: Fit trên text:', style='List Number')
doc.add_paragraph('tfidf.fit(text_data)', style='List Bullet 2')
doc.add_paragraph('Bước 3: Transform text → vectors:', style='List Number')
doc.add_paragraph('X_tfidf = tfidf.transform(text_data)', style='List Bullet 2')
doc.add_paragraph('Kết quả: Sparse matrix (docs × terms)', style='List Bullet')
doc.add_paragraph('Mỗi term có TF-IDF weight', style='List Bullet 2')

doc.add_heading('7. 3.2.6: Tạo Dữ Liệu Nhân Tạo & Cân Bằng (Synthetic Data)', 2)
doc.add_paragraph('Tại sao cần synthetic data:', style='List Bullet')
doc.add_paragraph('Dữ liệu thực tế thường imbalanced', style='List Bullet 2')
doc.add_paragraph('Hạn chế overfitting trên một class', style='List Bullet 2')
doc.add_paragraph('Cách tạo:', style='List Bullet')
doc.add_paragraph('Chọn random values cho mỗi trường', style='List Bullet 2')
doc.add_paragraph('Đảm bảo phân phối realistic', style='List Bullet 2')
doc.add_paragraph('Tạo ~1200 samples: 80 per major', style='List Bullet 2')
doc.add_paragraph('Kết quả: Balanced dataset', style='List Bullet')

doc.add_heading('8. Quy Trình Hoàn Chỉnh', 1)
doc.add_paragraph('Input: Raw CSV data', style='List Number')
doc.add_paragraph('Step 1: Load & inspect', style='List Number')
doc.add_paragraph('Step 2: Clean (missing, outliers)', style='List Number')
doc.add_paragraph('Step 3: Normalize text (Vietnamese)', style='List Number')
doc.add_paragraph('Step 4: Normalize categorical', style='List Number')
doc.add_paragraph('Step 5: One-Hot Encoding', style='List Number')
doc.add_paragraph('Step 6: TF-IDF Vectorization', style='List Number')
doc.add_paragraph('Output: Clean, normalized feature matrix', style='List Number')

doc.add_heading('9. Kết Luận', 1)
doc.add_paragraph('✓ Làm sạch dữ liệu → remove noise', style='List Bullet')
doc.add_paragraph('✓ Chuẩn hóa → consistent format', style='List Bullet')
doc.add_paragraph('✓ Encoding → machine-readable', style='List Bullet')
doc.add_paragraph('✓ Synthetic data → balanced dataset', style='List Bullet')
doc.add_paragraph('✓ Quality input → better model', style='List Bullet')

doc.save('DATA_PREPROCESSING_MODULE.docx')
print("✅ Data Preprocessing Module completed: DATA_PREPROCESSING_MODULE.docx")
